language: go
go:
  - 1.10
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - openssl aes-256-cbc -k "$conf_pass" -in encrypted/conf.enc -out ./server.conf.$server -d
  - openssl aes-256-cbc -k "$deploy_pass" -in encrypted/deploy.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $server\n\tPort $server_port\n\tUser $deploy_user\n\tStrictHostKeyChecking no\n\tLogLevel error\n" >> ~/.ssh/config
script:
  - ./build.sh
after_success:
  - goveralls -coverprofile=profile.cov -service=travis-ci
  - ./package.sh -D $server
env:
  global:
    - secure: BfLspDjXgf0k+WZAc5YgDrozNQgkpMEr8DRAJNJC/lUhNEulDs8xBIFDT8J0WII+PyEbc91AD9OB3L3SRLAXhdBhyHrNq/5oDLJEyzxoJWraPeehAjBSzpRTnumRYCjFs0Q68mY8tSeQOuAbRjOy6SxEvkmjJJ/VUQByQLNw3z0=
    - secure: KMy6YozI1Bsw/XqNm81cyJcHpyXERkIRW9ygfQKAcp1pZMxzQUdbPUNL1Sa24DtT4cCWzVMsBh6MWUoH/byKcQaj+Hy3pjfzycNIaIwhWHeBO0DvHGbexV9K0911gBhy/cChA5Kdh9qyw6GqZp1rF3GdmsJmN2AK62MfXbbUunI=
    - secure: XdFiXlMYTmEIhAHYQdb3D3Nmm6lJXNZiexgo28qwEYRna7IfMhREehXar1AWAF2RJ65Ahf8pkNOfinedygvqNiPDbwdhjzmnSa9MBPuTZsSZB/lnNRIhsQDR+8InEQuV+b+s//4A2Uy1bUcl1IkA/7uAoCISpRIQ8XF0i1FC7BE=
    - secure: gOUP2/3oOzfqqbQzwJ6eaoaQhtzPhIfZLMg9lMRh/2BzDtttos1/M4iVqJ/C7M6dSbPcPhXYWc4z6NbGmPaSah9EpMyrfp/4v1vRyNPgNZkb+fJETwh2K5jnIpXl3jn3mNBXucpYes6JECeFpMW4fF8tvCeRbAvAKCRUwIDWLEM=
    - secure: Cv3ykHcCCP+nPY+URnZwRX88Oz31TCRuWhR0tRh3t3rkW09e0U3uC5jaJXaO59o1S4liHrARhV01dDu0peiIQOXglJZY/ft9eCI8JlcmMU2kd9B/RD/fklc01Pv1iaAehj45pEMhV5/vmKm/0lWAeaj2C0pdrkdC+wj48awoM5w=
sudo: false
